import '../styles/globals.scss';
import '@rainbow-me/rainbowkit/styles.css';
import type { AppProps } from 'next/app';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { WagmiProvider } from 'wagmi';
import { RainbowKitProvider } from '@rainbow-me/rainbowkit';

import  Head from 'next/head';
import Layout from '../components/Layout';
import { ToastContainer, Zoom } from 'react-toastify';
import { ThemeProvider, createTheme } from '@mui/material/styles';

import { config } from '../utils/wagmi';

const client = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  const theme = createTheme();
  return (
    <>
      <Head>
        <title>Rcc Stake App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <WagmiProvider config={config}>
        <QueryClientProvider client={client}>
          <RainbowKitProvider>
            <ThemeProvider theme={theme}>
              <ToastContainer
                position="top-center"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme="light"
                transition={Zoom}
              />
              <Layout><Component {...pageProps} /></Layout>
            </ThemeProvider>
          </RainbowKitProvider>
        </QueryClientProvider>
      </WagmiProvider>
    </>
  );
}

export default MyApp;
